import {
  Activity,
  AppWindow,
  Archive,
  ArrowRightLeft,
  BarChart3,
  Blocks,
  Boxes,
  BrainCircuit,
  Cable,
  CircleDot,
  Cloud,
  Combine,
  Container,
  CopyCheck,
  Cpu,
  CreditCard,
  Database,
  DatabaseZap,
  FileCode2,
  FileSearch,
  Fingerprint,
  FolderInput,
  FolderTree,
  Gauge,
  Gavel,
  Globe,
  HardDrive,
  Hexagon,
  KeyRound,
  KeySquare,
  Layers,
  LifeBuoy,
  LineChart,
  Lock,
  LockKeyhole,
  PiggyBank,
  Network,
  Package,
  Radio,
  Rocket,
  Route,
  Router,
  Scale,
  ScanEye,
  ScrollText,
  Server,
  Settings2,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldHalf,
  Ship,
  Shuffle,
  Sparkles,
  Split,
  Table2,
  Terminal,
  Truck,
  Users,
  UserCog,
  Waypoints,
  Wind,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

// Maps the string `icon` keys used in curriculum.ts to Lucide components.
// Any missing key falls back to CircleDot (see iconFor).
const ICONS: Record<string, LucideIcon> = {
  // Pillars
  compute: Cpu,
  storage: Database,
  networking: Network,
  security: ShieldCheck,
  management: Settings2,
  "data-ai": BrainCircuit,

  // Compute
  gce: Server,
  gke: Blocks,
  "cloud-run": Container,
  "cloud-functions": Zap,
  "app-engine": Rocket,
  "persistent-disks": HardDrive,
  "spot-vms": Zap,
  "sole-tenant": Server,
  anthos: Hexagon,

  // Storage & Databases
  "cloud-sql": Database,
  spanner: Globe,
  bigtable: Table2,
  bigquery: BarChart3,
  firestore: Layers,
  "cloud-storage": Archive,
  memorystore: Zap,
  filestore: FolderTree,
  datastore: Database,

  // Networking
  vpc: Network,
  "cloud-lb": Waypoints,
  "cloud-cdn": Globe,
  "cloud-dns": Router,
  "cloud-interconnect": Cable,
  "cloud-nat": Router,
  "cloud-vpn": LockKeyhole,
  "cloud-router": Router,
  "shared-vpc": Share2,
  "vpc-peering": ArrowRightLeft,

  // Security
  iam: KeyRound,
  "vpc-sc": ShieldHalf,
  "cloud-kms": Lock,
  "secret-manager": KeySquare,
  "cloud-armor": Shield,
  "cloud-iap": Fingerprint,
  "cloud-identity": Users,
  "resource-manager": Layers,
  "service-accounts": UserCog,
  "org-policy": Gavel,
  scc: ShieldAlert,

  // Management & Ops
  "cloud-monitoring": Activity,
  "cloud-logging": ScrollText,
  "cloud-build": Wrench,
  "cloud-deploy": Ship,
  iac: FileCode2,
  dms: DatabaseZap,
  "ops-suite": Gauge,
  "audit-logs": FileSearch,
  "artifact-registry": Package,
  "cloud-shell": Terminal,
  "cloud-billing": CreditCard,
  "storage-transfer": FolderInput,
  "transfer-appliance": Truck,

  // Data & AI
  pubsub: Radio,
  dataflow: Workflow,
  dataproc: Blocks,
  looker: LineChart,
  "vertex-ai": Sparkles,
  "ai-apis": ScanEye,
  composer: Wind,
  datafusion: Combine,

  // Decision guides
  "decision-guides": Route,
  "hybrid-connectivity": Cable,
  "vpc-connectivity": Waypoints,
  "migration-path": ArrowRightLeft,
  "dr-strategy": LifeBuoy,
  "cost-optimization": PiggyBank,
  "ha-patterns": CopyCheck,
  "compute-chooser": Boxes,
  "lb-chooser": Split,
  "data-processing-chooser": Shuffle,
  "storage-chooser": HardDrive,
  "compliance-mapping": Scale,

  // Generic
  cloud: Cloud,
  app: AppWindow,
};

export function iconFor(key: string): LucideIcon {
  return ICONS[key] ?? CircleDot;
}
